### PR TITLE
Adds check for AA version

### LINKED ISSUE #8: Not working with ActiveAdmin v 1.4+
The monkey patching of ActiveAdmin::Views::Pages::Base is failing. The `@head` has been changed to just `head`

### PR DESCRIPTION
**Pull request by kjeldahl**
Fixes #8

### CODE REVIEW

**Comment by ball-hayden** [comment]
Ah. You have done! Awesome.

**Review by ball-hayden — APPROVED** [review]

**Comment by kjeldahl** [comment]
Can I convince you to bump the version and publish the gem?

**Comment by ball-hayden** [comment]
Sure. Done 🙂

**Comment by kjeldahl** [comment]
Thanks a lot 😊

**Pull request merged**
